name: Run tests on Linux and macOS
on:
  push:
  workflow_dispatch:

jobs:
  test_linux:
    if: true
    runs-on: ubuntu-24.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Swift test
        run: swift test

  test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Swift test
        run: swift test
